spring:
  datasource:
    dynamic:
      enabled: true
      strict: true
      primary: "master"


base:
  datasource:
    hikari:
      master:
        flyway:
          out-of-order: true

---
spring:
  config:
    activate:
      on-profile: suyh,suyh_mac

base:
  datasource:
    hikari:
      master:
        jdbc-url: jdbc:mysql://qu-yun.isuyh.com:3306/suyh_mortgage?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        username: suyh_mortgage
        password: suyh_mortgage
        flyway:
          enabled: true
          locations:
            - "sqls/mysql/sys/base"
            - "sqls/mortgage/mysql"





