
-- DROP TABLE IF EXISTS mortgage_repayment;
CREATE TABLE `mortgage_repayment`
(
    `id`                    bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID' PRIMARY KEY,
    `user_id`               bigint COMMENT '所属用户ID',
    `user_nick_name`        varchar(64) COMMENT '所属用户昵称',
    `loan_type`             tinyint        NOT NULL COMMENT '贷款类型：1-公积金贷款 2-商业贷款 3-组合贷款',
    `repayment_period`      int                     DEFAULT NULL COMMENT '还款期数',
    `actual_repayment_date` int            NOT NULL COMMENT '实际还款日期',
    `actual_principal`      decimal(15, 2) NOT NULL COMMENT '实际还款本金',
    `actual_interest`       decimal(15, 2) NOT NULL COMMENT '实际还款利息',
    `actual_overdue_fee`    decimal(15, 2)          DEFAULT '0.00' COMMENT '实际支付的逾期费用',
    `actual_total`          decimal(15, 2) GENERATED ALWAYS AS (((`actual_principal` + `actual_interest`) + `actual_overdue_fee`)) STORED COMMENT '实际还款总金额（自动计算）',
    `remaining_loan_amount` decimal(18, 2)          DEFAULT NULL COMMENT '还款后当前剩余贷款本金金额',
    `payment_method`        varchar(20)    NOT NULL COMMENT '还款方式：银行卡、支付宝、微信等',
    `payment_no`            varchar(50)             DEFAULT NULL COMMENT '支付单号/银行流水号',
    `actual_LPR`            decimal(4, 2)           DEFAULT NULL COMMENT '当前实际使用的贷款利率百分比，如：3.5%',
    `actual_BP`             decimal(5, 1)           DEFAULT NULL COMMENT '当前实际使用的基点，如：-30‱',
    `realtime_LPR`          decimal(4, 2)           DEFAULT NULL COMMENT '当前实时的贷款利率百分比，如：3.5%',
    `realtime_BP`           decimal(5, 1)           DEFAULT NULL COMMENT '当前实时的基点，如：-30‱',
    `remark`                varchar(500)            DEFAULT NULL COMMENT '备注（如：提前还款、组合贷公积金部分等）',
    `created`               datetime       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
    `updated`               datetime       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间'
) ENGINE=InnoDB COMMENT='房贷实际还款记录表（区分公积金/商业）';


INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 1, 20220924, 3532.77, 10472.67, 0.00,  NULL, '银行卡', '', NULL, NULL, 4.30, 30.0, NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 2, 20221024, 3546.32, 10459.12, 0.00,  NULL, '银行卡', '', NULL, NULL, 4.30, 30.0, NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 3, 20221124, 3559.91, 10445.53, 0.00,  NULL, '银行卡', '', NULL, NULL, 4.30, 30.0, NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 4, 20221224, 3573.56, 10431.88, 0.00,  NULL, '银行卡', '', NULL, NULL, 4.30, 30.0, NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 5, 20230124, 3587.25, 10418.19, 0.00,  NULL, '银行卡', '', NULL, NULL, 4.30, 30.0, NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 6, 20230224, 3601.01, 10404.43, 0.00,  NULL, '银行卡', '', NULL, NULL, 4.30, 30.0, NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 7, 20230324, 3614.81, 10390.63, 0.00,  NULL, '银行卡', '', NULL, NULL, 4.30, 30.0, NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 8, 20230424, 3628.66, 10376.78, 0.00,  NULL, '银行卡', '', NULL, NULL, 4.30, 30.0, NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 9, 20230524, 3642.58, 10362.86, 0.00,  NULL, '银行卡', '', NULL, NULL, 4.30, 30.0, NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 10, 20230624, 3656.54, 10348.90, 0.00, NULL, '银行卡', '', NULL, NULL, 4.30, 30.0, NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 11, 20230724, 3670.56, 10334.88, 0.00, NULL, '银行卡', '', NULL, NULL, 4.30, 30.0, NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 12, 20230824, 3684.62, 10320.82, 0.00, NULL, '银行卡', '', NULL, NULL, 4.30, 30.0, NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 13, 20230924, 3698.76, 10306.68, 0.00, NULL, '银行卡', '', NULL, NULL, 4.30, -10.0, NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 14, 20231024, 3712.93, 10292.51, 0.00, NULL, '银行卡', '', NULL, NULL, 4.30, -10.0, NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 15, 20231124, 3727.16, 10278.28, 0.00, NULL, '银行卡', '', NULL, NULL, 4.30, -10.0, NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 16, 20231224, 3741.45, 10263.99, 0.00, NULL, '银行卡', '', NULL, NULL, 4.30, -10.0, NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 17, 20240124, 3761.73, 10086.25, 0.00, NULL, '银行卡', '', NULL, NULL, 4.20, -10.0, NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 18, 20240224, 3835.26, 10012.72, 0.00, NULL, '银行卡', '', NULL, NULL, 4.20, -10.0, NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 19, 20240324, 3849.64, 9998.24, 0.00,   NULL, '银行卡', '', NULL, NULL, 4.20, -10.0,  NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 20, 20240424, 3864.08, 9983.90, 0.00,   NULL, '银行卡', '', NULL, NULL, 4.20, -10.0,  NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 21, 20240524, 3878.57, 9969.41, 0.00,   NULL, '银行卡', '', NULL, NULL, 3.95, -20.0,  NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 22, 20240624, 3893.11, 9954.87, 0.00,   NULL, '银行卡', '', NULL, NULL, 3.95, -20.0,  NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 23, 20240717, 660000.00, 1897.50, 0.00, NULL, '银行卡', '', NULL, NULL, 3.95, -20.0, NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 24, 20240724, 2934.98, 7465.27, 0.00,   NULL, '银行卡', '', NULL, NULL, 3.95, -20.0,   NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 25, 20240824, 2945.99, 7454.26, 0.00,   NULL, '银行卡', '', NULL, NULL, 3.95, -20.0,   NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 26, 20240924, 2957.03, 7443.22, 0.00,   NULL, '银行卡', '', NULL, NULL, 3.95, -20.0,   NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 27, 20241024, 9218.14, 7432.13, 0.00,   NULL, '银行卡', '', NULL, NULL, 3.95, -20.0,   NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 28, 20241124, 9218.14, 6444.10, 0.00,   NULL, '银行卡', '', NULL, NULL, 3.95, -20.0,   NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 29, 20241130, 350000.00, 227.50, 0.00,  NULL, '银行卡', '', NULL, NULL, 3.95, -20.0, NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 30, 20241224, 7574.95, 5243.76, 0.00,   NULL, '银行卡', '', NULL, NULL, 3.95, -20.0,   NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 31, 20250124, 7574.95, 4630.31, 0.00,   NULL, '银行卡', '', NULL, NULL, 3.60, -20.0,   NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 32, 20250224, 7574.95, 4395.36, 0.00,   NULL, '银行卡', '', NULL, NULL, 3.60, -20.0,   NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 33, 20250324, 7574.95, 4374.53, 0.00,   NULL, '银行卡', '', NULL, NULL, 3.60, -20.0,   NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 34, 20250424, 7574.95, 4353.70, 0.00,   NULL, '银行卡', '', NULL, NULL, 3.60, -20.0,   NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 35, 20250524, 7574.95, 4332.87, 0.00,   NULL, '银行卡', '', NULL, NULL, 3.50, -45.0,   NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 36, 20250624, 7574.95, 4312.04, 0.00,   NULL, '银行卡', '', NULL, NULL, 3.50, -45.0,   NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 37, 20250704, 100000.00, 91.67, 0.00,   NULL, '银行卡', '', NULL, NULL, 3.50, -45.0,  NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 38, 20250724, 7089.51, 4016.20, 0.00,   NULL, '银行卡', '', NULL, NULL, 3.50, -45.0,   NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 39, 20250824, 12011.16, 3996.71, 0.00,  NULL, '银行卡', '', NULL, NULL, 3.50, -45.0,  NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 40, 20250924, 12011.16, 3963.68, 0.00,  NULL, '银行卡', '', NULL, NULL, 3.50, -45.0,  NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 41, 20251024, 12011.16, 3930.65, 0.00,  NULL, '银行卡', '', NULL, NULL, 3.50, -45.0,  NULL);
INSERT INTO `mortgage_repayment` (`loan_type`, `repayment_period`, `actual_repayment_date`, `actual_principal`, `actual_interest`, `actual_overdue_fee`, `remaining_loan_amount`, `payment_method`, `payment_no`, `actual_LPR`, `actual_BP`, `realtime_LPR`, `realtime_BP`, `remark`) VALUES (1, 42, 20251124, 12011.16, 3897.62, 0.00,  1405305.64, '银行卡', '', NULL, NULL, 3.50, -45.0, NULL);
